export default [
  "Accounting",
  "Computer & Equipment",
  "Entertainment",
  "Hosting/Domains",
  "Home Office Utilities",
  "Contractor",
  "Home Office Expense",
  "Internet",
  "Mobile",
  "Misc",
  "Petrol",
  "Stationery",
  "Travel",
  "Vehicle",
];
